

IF NOT EXISTS(SELECT 1 FROM sys.columns 
          WHERE Name = N'nIdAgenteAduanal033'
          AND Object_ID = Object_ID(N'WMS.WMS_001_REFERENCIA'))
BEGIN

    ALTER TABLE [WMS].[WMS_001_REFERENCIA] ADD nIdAgenteAduanal033 INT NULL;

    ALTER TABLE [WMS].[WMS_001_REFERENCIA]  WITH CHECK ADD  CONSTRAINT [FK_WMS_001_REFERENCIA_WMS_033_AGENTE_ADUANAL_nIdAgenteAduanal033] FOREIGN KEY([nIdAgenteAduanal033])
	REFERENCES [WMS].[WMS_033_AGENTE_ADUANAL] ([nIdAgenteAduanal033])

	ALTER TABLE [WMS].[WMS_001_REFERENCIA] CHECK CONSTRAINT [FK_WMS_001_REFERENCIA_WMS_033_AGENTE_ADUANAL_nIdAgenteAduanal033]

END

