
CREATE TABLE [WMS].[WMS_034_REFERENCIA_BOOKING_BL](
	[nIdReferenciaBookingBl034] [int] IDENTITY(1,1) NOT NULL,
	[sBookingBl] [nvarchar](50) NULL,
	[nIdReferencia001] [int] NULL,
	[dFechaAlta] [datetime2](7) NULL,
 CONSTRAINT [PK_WMS_034_REFERENCIA_BOOKING_BL] PRIMARY KEY CLUSTERED 
(
	[nIdReferenciaBookingBl034] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]


ALTER TABLE [WMS].[WMS_034_REFERENCIA_BOOKING_BL]  WITH CHECK ADD  CONSTRAINT [FK_WMS_034_REFERENCIA_BOOKING_BL_WMS_001_REFERENCIA_nIdReferencia001] FOREIGN KEY([nIdReferencia001])
REFERENCES [WMS].[WMS_001_REFERENCIA] ([nIdReferencia001])


ALTER TABLE [WMS].[WMS_034_REFERENCIA_BOOKING_BL] CHECK CONSTRAINT [FK_WMS_034_REFERENCIA_BOOKING_BL_WMS_001_REFERENCIA_nIdReferencia001]



