

IF NOT EXISTS(SELECT 1 FROM sys.columns 
          WHERE Name = N'nIdManiobristaOrigen023'
          AND Object_ID = Object_ID(N'WMS.WMS_001_REFERENCIA'))
BEGIN

    ALTER TABLE [WMS].[WMS_001_REFERENCIA] ADD nIdManiobristaOrigen023 INT NULL;

    ALTER TABLE [WMS].[WMS_001_REFERENCIA]  WITH CHECK ADD  CONSTRAINT [FK_WMS_001_REFERENCIA_WMS_023_MANIOBRISTA_nIdManiobristaOrigen023] FOREIGN KEY([nIdManiobristaOrigen023])
REFERENCES [WMS].[WMS_023_MANIOBRISTA] ([nIdManiobrista023])


    ALTER TABLE [WMS].[WMS_001_REFERENCIA] CHECK CONSTRAINT [FK_WMS_001_REFERENCIA_WMS_023_MANIOBRISTA_nIdManiobristaOrigen023]


END
GO

--COMMIT;
