
GO

/****** Object:  Table [WMS].[WMS_040_SALIDA_CONTROL_TRANSPORTE]    Script Date: 06/04/2025 16:03:11 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [WMS].[WMS_040_SALIDA_CONTROL_TRANSPORTE](
	[nIdSalidaControlTransporte040] [int] IDENTITY(1,1) NOT NULL,
	[nIdOrdenSalida035] [int] NULL,
	[nIdSalida039] [int] NULL,
	[nIdControlTransporte024] [int] NULL,
	[bActivo] [bit] NOT NULL,
	[dFechaCancelacion] [datetime2](7) NULL,
	[sMotivoCancelacion] [nvarchar](4000) NULL,
	[nIdCatUsuarioCancelacion] [int] NULL,
	[dFechaAlta] [datetime2](7) NULL,
 CONSTRAINT [PK_WMS_040_SALIDA_CONTROL_TRANSPORTE] PRIMARY KEY CLUSTERED 
(
	[nIdSalidaControlTransporte040] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [WMS].[WMS_040_SALIDA_CONTROL_TRANSPORTE]  WITH CHECK ADD  CONSTRAINT [FK_WMS_040_SALIDA_CONTROL_TRANSPORTE_CatUsuarios_nIdCatUsuarioCancelacion] FOREIGN KEY([nIdCatUsuarioCancelacion])
REFERENCES [dbo].[catUsuarios] ([IdCatUsuarios])
GO

ALTER TABLE [WMS].[WMS_040_SALIDA_CONTROL_TRANSPORTE] CHECK CONSTRAINT [FK_WMS_040_SALIDA_CONTROL_TRANSPORTE_CatUsuarios_nIdCatUsuarioCancelacion]
GO

ALTER TABLE [WMS].[WMS_040_SALIDA_CONTROL_TRANSPORTE]  WITH CHECK ADD  CONSTRAINT [FK_WMS_040_SALIDA_CONTROL_TRANSPORTE_WMS_024_CONTROL_TRANSPORTE_nIdControlTransporte024] FOREIGN KEY([nIdControlTransporte024])
REFERENCES [WMS].[WMS_024_CONTROL_TRANSPORTE] ([nIdControlTransporte024])
GO

ALTER TABLE [WMS].[WMS_040_SALIDA_CONTROL_TRANSPORTE] CHECK CONSTRAINT [FK_WMS_040_SALIDA_CONTROL_TRANSPORTE_WMS_024_CONTROL_TRANSPORTE_nIdControlTransporte024]
GO

ALTER TABLE [WMS].[WMS_040_SALIDA_CONTROL_TRANSPORTE]  WITH CHECK ADD  CONSTRAINT [FK_WMS_040_SALIDA_CONTROL_TRANSPORTE_WMS_035_ORDEN_SALIDA_nIdOrdenSalida035] FOREIGN KEY([nIdOrdenSalida035])
REFERENCES [WMS].[WMS_035_ORDEN_SALIDA] ([nIdOrdenSalida035])
GO

ALTER TABLE [WMS].[WMS_040_SALIDA_CONTROL_TRANSPORTE] CHECK CONSTRAINT [FK_WMS_040_SALIDA_CONTROL_TRANSPORTE_WMS_035_ORDEN_SALIDA_nIdOrdenSalida035]
GO

ALTER TABLE [WMS].[WMS_040_SALIDA_CONTROL_TRANSPORTE]  WITH CHECK ADD  CONSTRAINT [FK_WMS_040_SALIDA_CONTROL_TRANSPORTE_WMS_039_SALIDA_nIdSalida039] FOREIGN KEY([nIdSalida039])
REFERENCES [WMS].[WMS_039_SALIDA] ([nIdSalida039])
GO

ALTER TABLE [WMS].[WMS_040_SALIDA_CONTROL_TRANSPORTE] CHECK CONSTRAINT [FK_WMS_040_SALIDA_CONTROL_TRANSPORTE_WMS_039_SALIDA_nIdSalida039]
GO


