
GO

/****** Object:  Table [WMS].[WMS_036_LIBERACION]    Script Date: 06/04/2025 15:58:45 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [WMS].[WMS_036_LIBERACION](
	[nIdLiberacion036] [int] IDENTITY(1,1) NOT NULL,
	[nIdReferencia001] [int] NULL,
	[nIdOrdenSalida035] [int] NULL,
	[nIdCatCliente] [int] NULL,
	[nIdAgenteAduanal033] [int] NULL,
	[nIdManiobristaDestino023] [int] NULL,
	[dFechaAlta] [datetime2](7) NULL,
 CONSTRAINT [PK_WMS_036_LIBERACION] PRIMARY KEY CLUSTERED 
(
	[nIdLiberacion036] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [WMS].[WMS_036_LIBERACION]  WITH CHECK ADD  CONSTRAINT [FK_WMS_036_LIBERACION_CatClientes_nIdCatCliente] FOREIGN KEY([nIdCatCliente])
REFERENCES [dbo].[catClientes] ([IdCatCliente])
GO

ALTER TABLE [WMS].[WMS_036_LIBERACION] CHECK CONSTRAINT [FK_WMS_036_LIBERACION_CatClientes_nIdCatCliente]
GO

ALTER TABLE [WMS].[WMS_036_LIBERACION]  WITH CHECK ADD  CONSTRAINT [FK_WMS_036_LIBERACION_WMS_001_REFERENCIA_nIdReferencia001] FOREIGN KEY([nIdReferencia001])
REFERENCES [WMS].[WMS_001_REFERENCIA] ([nIdReferencia001])
GO

ALTER TABLE [WMS].[WMS_036_LIBERACION] CHECK CONSTRAINT [FK_WMS_036_LIBERACION_WMS_001_REFERENCIA_nIdReferencia001]
GO

ALTER TABLE [WMS].[WMS_036_LIBERACION]  WITH CHECK ADD  CONSTRAINT [FK_WMS_036_LIBERACION_WMS_023_MANIOBRISTA_nIdManiobristaDestino023] FOREIGN KEY([nIdManiobristaDestino023])
REFERENCES [WMS].[WMS_023_MANIOBRISTA] ([nIdManiobrista023])
GO

ALTER TABLE [WMS].[WMS_036_LIBERACION] CHECK CONSTRAINT [FK_WMS_036_LIBERACION_WMS_023_MANIOBRISTA_nIdManiobristaDestino023]
GO

ALTER TABLE [WMS].[WMS_036_LIBERACION]  WITH CHECK ADD  CONSTRAINT [FK_WMS_036_LIBERACION_WMS_033_AGENTE_ADUANAL_nIdAgenteAduanal033] FOREIGN KEY([nIdAgenteAduanal033])
REFERENCES [WMS].[WMS_033_AGENTE_ADUANAL] ([nIdAgenteAduanal033])
GO

ALTER TABLE [WMS].[WMS_036_LIBERACION] CHECK CONSTRAINT [FK_WMS_036_LIBERACION_WMS_033_AGENTE_ADUANAL_nIdAgenteAduanal033]
GO

ALTER TABLE [WMS].[WMS_036_LIBERACION]  WITH CHECK ADD  CONSTRAINT [FK_WMS_036_LIBERACION_WMS_035_ORDEN_SALIDA_nIdOrdenSalida035] FOREIGN KEY([nIdOrdenSalida035])
REFERENCES [WMS].[WMS_035_ORDEN_SALIDA] ([nIdOrdenSalida035])
GO

ALTER TABLE [WMS].[WMS_036_LIBERACION] CHECK CONSTRAINT [FK_WMS_036_LIBERACION_WMS_035_ORDEN_SALIDA_nIdOrdenSalida035]
GO


