
GO

/****** Object:  Table [WMS].[WMS_038_LIBERACION_INVENTARIO]    Script Date: 06/04/2025 15:59:42 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [WMS].[WMS_038_LIBERACION_INVENTARIO](
	[nIdLiberacionInventario038] [int] IDENTITY(1,1) NOT NULL,
	[nIdOrdenSalidaInventario037] [int] NULL,
	[nIdTarja015] [int] NULL,
	[nNumeroPartida] [int] NOT NULL,
	[nPeso] [decimal](18, 2) NULL,
	[nCantidad] [int] NULL,
	[bLiberacionParcial] [bit] NOT NULL,
	[dFechaAlta] [datetime2](7) NULL,
 CONSTRAINT [PK_WMS_038_LIBERACION_INVENTARIO] PRIMARY KEY CLUSTERED 
(
	[nIdLiberacionInventario038] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [WMS].[WMS_038_LIBERACION_INVENTARIO]  WITH CHECK ADD  CONSTRAINT [FK_WMS_038_LIBERACION_INVENTARIO_WMS_015_TARJA_nIdTarja015] FOREIGN KEY([nIdTarja015])
REFERENCES [WMS].[WMS_015_TARJA] ([nIdTarja015])
GO

ALTER TABLE [WMS].[WMS_038_LIBERACION_INVENTARIO] CHECK CONSTRAINT [FK_WMS_038_LIBERACION_INVENTARIO_WMS_015_TARJA_nIdTarja015]
GO


