
GO

/****** Object:  Table [WMS].[WMS_037_ORDEN_SALIDA_INVENTARIO]    Script Date: 06/04/2025 15:59:19 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [WMS].[WMS_037_ORDEN_SALIDA_INVENTARIO](
	[nIdOrdenSalidaInventario037] [int] IDENTITY(1,1) NOT NULL,
	[nIdOrdenSalida035] [int] NULL,
	[nIdInventario014] [int] NULL,
	[dFechaAlta] [datetime2](7) NULL,
 CONSTRAINT [PK_WMS_037_ORDEN_SALIDA_INVENTARIO] PRIMARY KEY CLUSTERED 
(
	[nIdOrdenSalidaInventario037] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [WMS].[WMS_037_ORDEN_SALIDA_INVENTARIO]  WITH CHECK ADD  CONSTRAINT [FK_WMS_037_ORDEN_SALIDA_INVENTARIO_WMS_014_INVENTARIO_nIdInventario014] FOREIGN KEY([nIdInventario014])
REFERENCES [WMS].[WMS_014_INVENTARIO] ([nIdInventario014])
GO

ALTER TABLE [WMS].[WMS_037_ORDEN_SALIDA_INVENTARIO] CHECK CONSTRAINT [FK_WMS_037_ORDEN_SALIDA_INVENTARIO_WMS_014_INVENTARIO_nIdInventario014]
GO

ALTER TABLE [WMS].[WMS_037_ORDEN_SALIDA_INVENTARIO]  WITH CHECK ADD  CONSTRAINT [FK_WMS_037_ORDEN_SALIDA_INVENTARIO_WMS_035_ORDEN_SALIDA_nIdOrdenSalida035] FOREIGN KEY([nIdOrdenSalida035])
REFERENCES [WMS].[WMS_035_ORDEN_SALIDA] ([nIdOrdenSalida035])
GO

ALTER TABLE [WMS].[WMS_037_ORDEN_SALIDA_INVENTARIO] CHECK CONSTRAINT [FK_WMS_037_ORDEN_SALIDA_INVENTARIO_WMS_035_ORDEN_SALIDA_nIdOrdenSalida035]
GO


