
GO

/****** Object:  Table [WMS].[WMS_039_SALIDA]    Script Date: 06/04/2025 16:02:49 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [WMS].[WMS_039_SALIDA](
	[nIdSalida039] [int] IDENTITY(1,1) NOT NULL,
	[nIdOrdenSalida035] [int] NULL,
	[nFolio] [int] NOT NULL,
	[nEstado] [int] NOT NULL,
	[dFechaSalida] [datetime2](7) NULL,
	[dFechaSalidaManual] [datetime2](7) NULL,
	[sMotivoCancelacion] [nvarchar](4000) NULL,
	[nIdCatEmpresa] [int] NOT NULL,
	[dFechaAlta] [datetime2](7) NULL,
 CONSTRAINT [PK_WMS_039_SALIDA] PRIMARY KEY CLUSTERED 
(
	[nIdSalida039] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [WMS].[WMS_039_SALIDA]  WITH CHECK ADD  CONSTRAINT [FK_WMS_039_SALIDA_CatEmpresas_nIdCatEmpresa] FOREIGN KEY([nIdCatEmpresa])
REFERENCES [dbo].[catEmpresas] ([IdCatEmpresa])
ON DELETE CASCADE
GO

ALTER TABLE [WMS].[WMS_039_SALIDA] CHECK CONSTRAINT [FK_WMS_039_SALIDA_CatEmpresas_nIdCatEmpresa]
GO

ALTER TABLE [WMS].[WMS_039_SALIDA]  WITH CHECK ADD  CONSTRAINT [FK_WMS_039_SALIDA_WMS_035_ORDEN_SALIDA_nIdOrdenSalida035] FOREIGN KEY([nIdOrdenSalida035])
REFERENCES [WMS].[WMS_035_ORDEN_SALIDA] ([nIdOrdenSalida035])
GO

ALTER TABLE [WMS].[WMS_039_SALIDA] CHECK CONSTRAINT [FK_WMS_039_SALIDA_WMS_035_ORDEN_SALIDA_nIdOrdenSalida035]
GO


